src/AppBundle/Entity/School.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * School
 *
 * @ORM\Table(name="school")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\SchoolRepository")
 */
class School
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="address", type="string", length=255)
     * @Assert\NotNull()
     */
    private $address;

    /**
     * @var string
     *
     * @ORM\Column(name="city", type="string", length=255)
     * @Assert\NotNull()
     */
    private $city;

    /**
     * @var string
     *
     * @ORM\Column(name="postcode", type="string", length=10)
     * @Assert\NotNull()
     */
    private $postcode;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     * @Assert\NotNull()
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="phone_number", type="string", length=255)
     * @Assert\NotNull()
     */
    private $phone_number;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     * @Assert\NotNull()
     */
    private $description;

    /**
     * @var integer
     * @ORM\ManyToOne(targetEntity="UserBundle\Entity\User", inversedBy="schools")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotNull()
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="BackBundle\Entity\Employee", mappedBy="school", cascade={"remove"})
     */
    private $employees;

    /**
     * @ORM\OneToMany(targetEntity="BackBundle\Entity\Student", mappedBy="school", cascade={"remove"})
     */
    private $students;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Pricing", mappedBy="school", cascade={"remove"})
     */
    private $pricings;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Payment", mappedBy="school", cascade={"remove"})
     */
    private $payments;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Ad", mappedBy="school", cascade={"remove"})
     */
    private $ads;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Vehicle", mappedBy="school", cascade={"remove"})
     */
    private $vehicles;

    public function getRegistrationPricings()
    {
        $pricings = array();

        foreach ($this->pricings as $pricing) {

            if ("Tarif inscription" == $pricing->getPricingCategory()->getName()) {
                $pricings[] = $pricing;
            }
        }

        return $pricings;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set address
     *
     * @param string $address
     * @return School
     */
    public function setAddress($address)
    {
        $this->address = $address;

        return $this;
    }

    /**
     * Get address
     *
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Set city
     *
     * @param string $city
     * @return School
     */
    public function setCity($city)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Get city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Set postcode
     *
     * @param string $postcode
     * @return School
     */
    public function setPostcode($postcode)
    {
        $this->postcode = $postcode;

        return $this;
    }

    /**
     * Get postcode
     *
     * @return string
     */
    public function getPostcode()
    {
        return $this->postcode;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return School
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return School
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set user
     *
     * @param \UserBundle\Entity\User $user
     * @return School
     */
    public function setUser(\UserBundle\Entity\User $user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \UserBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set phone_number
     *
     * @param string $phoneNumber
     * @return School
     */
    public function setPhoneNumber($phoneNumber)
    {
        $this->phone_number = $phoneNumber;

        return $this;
    }

    /**
     * Get phone_number
     *
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->phone_number;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->pricings = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add pricings
     *
     * @param \AppBundle\Entity\Pricing $pricings
     * @return School
     */
    public function addPricing(\AppBundle\Entity\Pricing $pricings)
    {
        $this->pricings[] = $pricings;

        return $this;
    }

    /**
     * Remove pricings
     *
     * @param \AppBundle\Entity\Pricing $pricings
     */
    public function removePricing(\AppBundle\Entity\Pricing $pricings)
    {
        $this->pricings->removeElement($pricings);
    }

    /**
     * Get pricings
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPricings()
    {
        return $this->pricings;
    }

    /**
     * Add payments
     *
     * @param \AppBundle\Entity\Payment $payments
     * @return School
     */
    public function addPayment(\AppBundle\Entity\Payment $payments)
    {
        $this->payments[] = $payments;

        return $this;
    }

    /**
     * Remove payments
     *
     * @param \AppBundle\Entity\Payment $payments
     */
    public function removePayment(\AppBundle\Entity\Payment $payments)
    {
        $this->payments->removeElement($payments);
    }

    /**
     * Get payments
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPayments()
    {
        return $this->payments;
    }

    /**
     * Add employees
     *
     * @param \BackBundle\Entity\Employee $employees
     * @return School
     */
    public function addEmployee(\BackBundle\Entity\Employee $employees)
    {
        $this->employees[] = $employees;

        return $this;
    }

    /**
     * Remove employees
     *
     * @param \BackBundle\Entity\Employee $employees
     */
    public function removeEmployee(\BackBundle\Entity\Employee $employees)
    {
        $this->employees->removeElement($employees);
    }

    /**
     * Get employees
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getEmployees()
    {
        return $this->employees;
    }

    /**
     * Add students
     *
     * @param \BackBundle\Entity\Student $students
     * @return School
     */
    public function addStudent(\BackBundle\Entity\Student $students)
    {
        $this->students[] = $students;

        return $this;
    }

    /**
     * Remove students
     *
     * @param \BackBundle\Entity\Student $students
     */
    public function removeStudent(\BackBundle\Entity\Student $students)
    {
        $this->students->removeElement($students);
    }

    /**
     * Get students
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getStudents()
    {
        return $this->students;
    }

    /**
     * Add ads
     *
     * @param \AppBundle\Entity\Ad $ads
     * @return School
     */
    public function addAd(\AppBundle\Entity\Ad $ads)
    {
        $this->ads[] = $ads;

        return $this;
    }

    /**
     * Remove ads
     *
     * @param \AppBundle\Entity\Ad $ads
     */
    public function removeAd(\AppBundle\Entity\Ad $ads)
    {
        $this->ads->removeElement($ads);
    }

    /**
     * Get ads
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getAds()
    {
        return $this->ads;
    }

    /**
     * Get vehicles
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getVehicles()
    {
        return $this->vehicles;
    }
}

src/AppBundle/Controller/SchoolsController.php
<?php

namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\Request;

use AppBundle\Entity\School;
use AppBundle\Entity\Payment;
use AppBundle\Form\PaymentType;

class SchoolsController extends BaseController
{
    /**
     * @Route("/auto-ecoles", name="front_schools")
     * @Method({"GET"})
     */
    public function indexAction(Request $request)
    {
        $schoolsRepository = $this->getRepository('AppBundle:School');
        $query = $schoolsRepository->getSchoolsQuery();

        $pagination = $this->getPaginator()->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', 1)/*page number*/,
            10/*limit per page*/
        );

        return $this->render('AppBundle:Schools:index.html.twig', array(
                'schools' => $pagination
            )
        );
    }

    /**
     * @Route("/auto-ecoles/{id}", requirements={"id" = "\d+"}, name="front_schools_show")
     * @ParamConverter("school", class="AppBundle:School", options={"id" = "id"})
     * @Method({"GET"})
     */
    public function showAction(School $school) {
        $paymentForm = $this->createForm(PaymentType::class, new Payment(), array('school_id' => $school->getId()));

        $ads = array();

        foreach ($school->getAds() as $ad) {
            $ads[$ad->getAdType()->getName()] = $ad;
        }

        return $this->render('AppBundle:Schools:show.html.twig', array(
                'school'      => $school,
                'paymentForm' => $paymentForm->createView(),
                'ads'         => $ads
            )
        );
    }
}

src/AppBundle/Resources/views/Schools/index.html.twig
{% extends "::base.html.twig" %}

{% block body %}
    <div class="bloc grey">
        <div class="container">
            <h1>Liste des auto écoles</h1>

            {% for school in schools %}
                <div class="col-lg-4">
                    <div class="school">
                        <h2>{{ school.name }}</h2>
                        <p>{{ school.description|slice(0, 100) }}...</p>
                        <a href="{{ path('front_schools_show', { id: school.id }) }}" class="read-more">Voir</a>
                    </div>
                </div>
            {% endfor %}

            {{ knp_pagination_render(schools) }}
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Schools/show.html.twig
{% extends "::base.html.twig" %}

{% block body %}
    <div class="container">
        {% if ads['Header'] is defined %}
            <div class="ad-bloc">
                <a target="_blank" href="{{ ads['Header'].url }}">
                    <img class="img-responsive" style="margin: 0 auto" src="{{ asset('uploads/school_' ~ school.id ~ '/' ~ ads['Header'].fileName) }}"/>
                </a>
                <span class="ads-mention">Publicité</span>
            </div>
        {% endif %}
        <div class="col-md-3">
            {% if ads['Sidebar1'] is defined %}
                <div class="ad-bloc">
                    <aside>
                        <a target="_blank" href="{{ ads['Sidebar1'].url }}">
                            <img class="img-responsive" style="margin: 0 auto" src="{{ asset('uploads/school_' ~ school.id ~ '/' ~ ads['Sidebar1'].fileName) }}"/>
                        </a>
                        <span class="ads-mention">Publicité</span>
                    </aside>
                </div>
            {% endif %}

            {% if ads['Sidebar2'] is defined %}
                <div class="ad-bloc">
                    <aside>
                        <a target="_blank" href="{{ ads['Sidebar2'].url }}">
                            <img class="img-responsive" style="margin: 0 auto" src="{{ asset('uploads/school_' ~ school.id ~ '/' ~ ads['Sidebar2'].fileName) }}"/>
                        </a>
                        <span class="ads-mention">Publicité</span>
                    </aside>
                </div>
            {% endif %}
        </div>
        <div class="col-md-9 school-content">
            <h1>{{ school.name }}</h1>

            <p>{{ school.description }}</p>

            {% if school.vehicles|length > 0 %}
                <h2 class="text-left">Les véhicules de cette auto-école</h2>
                {% for vehicle in school.vehicles %}
                    <div class="col-lg-3">
                        <div class="panel panel-default car-bloc">
                            <h3 class="car-title">{{ vehicle.brand}} - {{ vehicle.ref }}</h3>
                            <img src="https://www.renault.ch/media/univers-pro-vu/gamme/attcf51508cf9da467a95ed5291874699f3/Clio_4.jpg" />
                            <!--<p>{{ vehicle.description }}</p>-->
                        </div>
                    </div>
                {% endfor %}
            {% endif %}

            {% if school.registrationPricings|length != 0 %}
                {% if app.user %}
                    <a href="#">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#paymentModal">
                            S'inscrire à cette auto école
                        </button>
                    </a>
                {% else %}
                    <a class="btn btn-success" href={{ path('fos_user_security_login')}}>
                        Connectez-vous pour vous inscrire
                    </a>
                {% endif %}
            {% endif %}
        </div>
        {% if ads['Footer'] is defined %}
            <div class="ad-bloc">
                <aside>
                    <a target="_blank" href="{{ ads['Footer'].url }}">
                        <img class="img-responsive" style="margin: 0 auto" src="{{ asset('uploads/school_' ~ school.id ~ '/' ~ ads['Footer'].fileName) }}"/>
                    </a>
                    <span class="ads-mention">Publicité</span>
                </aside>
            </div>
        {% endif %}
    </div>
    <div class="modal fade" id="paymentModal" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Valider votre inscription</h4>
                </div>
                {{ form_start(paymentForm, { attr: { action: path('front_schools_payments_create', { 'school_id': school.id }) }}) }}
                <div class="modal-body">
                    <div class="form-group">
                        {{ form_label(paymentForm.pricing) }}
                        {{ form_widget(paymentForm.pricing, { attr: { class: 'form-control' }} ) }}
                    </div>
                    <div class="form-group">
                        {{ form_label(paymentForm.credit_card_number) }}
                        {{ form_widget(paymentForm.credit_card_number, { attr: { class: 'form-control' }} ) }}
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                {{ form_label(paymentForm.credit_card_month) }}
                                {{ form_widget(paymentForm.credit_card_month, { attr: { class: 'form-control' }} ) }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                {{ form_label(paymentForm.credit_card_day) }}
                                {{ form_widget(paymentForm.credit_card_day, { attr: { class: 'form-control' }} ) }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form_label(paymentForm.credit_card_code) }}
                        {{ form_widget(paymentForm.credit_card_code, { attr: { class: 'form-control' }} ) }}
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
                    <button type="submit" class="btn btn-primary">Payer et valider</button>
                </div>
                {{ form_end(paymentForm) }}
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
</div>
{% endblock %}